version: "3.8"

services:
  chatbot:
    build: .
    container_name: chatbot
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app/app:ro   # optional: mount app as read-only to see code quickly (remove for strict container)
